### PR TITLE
fix: Workaround the Rust compiler 1.90.0 regression

### PR DESCRIPTION
**Pull request by Kontinuation**
We've worked around the Rust compiler 1.90.0 regression in its forked dependency wherobots/geo: https://github.com/wherobots/geo/pull/11. Please refer to the description of that PR for details.

Once we resolve the compilation issue, we'll start working on moving geo-traits-ext and geo-generic-alg modules into the sedona-db repository, and get rid of our own geo, wkb, and wkt fork. This will unblock us from publishing our sedona-db crate to crates.io, and make the project grow in a healthier state.

### CODE REVIEW

File: r/sedonadb/src/Makevars.in [hunk 1]
```diff
@@ -40,7 +40,6 @@ $(STATLIB):
 	# therefore is only used if cargo is absent from the user's PATH.
 	export PATH="$(PATH):$(HOME)/.cargo/bin" && \
 	  export CC="$(CC)" && \
-	  export CFLAGS="$(CFLAGS)" && \
```
Comment (Kontinuation) [inline r/sedonadb/src/Makevars.in:43]: I am removing this because it triggers a problem after upgrading `aws-lc-sys` from 0.31.0 to 0.32.0. aws-lc requires that the jitterentropy module be compiled without compiler optimization enabled (see https://github.com/aws/aws-lc/blob/2449607d740a5a8168c8a1366a57a3d91c80b16c/third_party/jitterentropy/jitterentropy-library/src/jitterentropy-base.c#L46-L48). Setting CFLAGS will result in the following error:

```
cargo:warning=/Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.32.0/aws-lc/third_party/jitterentropy/jitterentropy-library/src/jitterentropy-base.c:47:3: error: "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
  cargo:warning=   47 |  #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
  cargo:warning=      |   ^
  cargo:warning=1 error generated.
  exit status: 1
```

The CMakeLists.txt of jitterentropy module explicitly disabled compiler optimization (https://github.com/aws/aws-lc/blob/2449607d740a5a8168c8a1366a57a3d91c80b16c/third_party/jitterentropy/CMakeLists.txt), we don't want to mess it up by setting up CFLAGS.

Comment (yutannihilation) [reply r/sedonadb/src/Makevars.in:43]: (Just a comment and I'm no expert here...)
Sorry for the trouble. I checked why I put `CFLAGS` here, and I think removing `CFLAGS` is fine because `CFLAGS` is not necessary in most cases.

One exception is when building the R package for [webR](https://docs.r-wasm.org/webr/latest/). So, at first, I added `CFLAGS` only on the webR case. But, later in https://github.com/yutannihilation/savvy/commit/b0fa0bb9c53270eec7ffa32bc105ecad89d6709a, I tweaked the `Makevars` to always add `CFLAGS` in the assumption it is harmless. I think the intension was to simplify the code, so there's no strong reason to use `CFLAGS` (at least until the day when sedona-db targets web browsers.)

Comment (paleolimbot) [reply r/sedonadb/src/Makevars.in:43]: In general we really do want to pass CFLAGS here (for cross-compilation as Hiroaki noted, but also for include flags passed from a user to workaround build failures).

How about: `AWS_LC_SYS_CFLAGS=$(CFLAGS) -O0`?

https://github.com/aws/aws-lc-rs/blob/ee368e0689b2a0aee973e2d5be50a2c8d8b64374/aws-lc-sys/builder/main.rs#L144-L146

(If that doesn't work feel free to just remove it like you've done here and I'll iterate on getting this to work)

File: Cargo.lock [hunk 2]
```diff
@@ -2652,7 +2653,7 @@ dependencies = [
 [[package]]
 name = "geo-traits"
 version = "0.2.0"
-source = "git+https://github.com/wherobots/geo.git?branch=generic-alg#a2a4d2d716f637da60eeb29731bd4415af784f76"
+source = "git+https://github.com/wherobots/geo.git?branch=generic-alg#66ff85949a82549b0d28fb2d4fae01e3ea19ca83"
```
Comment (paleolimbot) [inline Cargo.lock:2656]: I am guessing this is the fix?

**Review by paleolimbot — APPROVED** [review]
Thank you!

File: r/sedonadb/src/Makevars.in (hunk 1 above)
Comment (paleolimbot) [reply r/sedonadb/src/Makevars.in:43]: Or maybe `AWS_LC_SYS_CMAKE_BUILDER`: https://github.com/aws/aws-lc-rs/blob/ee368e0689b2a0aee973e2d5be50a2c8d8b64374/aws-lc-sys/builder/main.rs#L592C18-L592C42

Comment (Kontinuation) [reply r/sedonadb/src/Makevars.in:43]: I have reverted this change and set`AWS_LC_SYS_CMAKE_BUILDER=1`.

File: Cargo.lock (hunk 2 above)
Comment (Kontinuation) [reply Cargo.lock:2656]: Yes.

File: r/sedonadb/src/Makevars.in (hunk 1 above)
Comment (paleolimbot) [reply r/sedonadb/src/Makevars.in:43]: It worked!

Comment (Kontinuation) [reply r/sedonadb/src/Makevars.in:43]: It is strange that [`prepare_jitter_entropy_builder`](https://github.com/aws/aws-lc-rs/blob/ee368e0689b2a0aee973e2d5be50a2c8d8b64374/aws-lc-sys/builder/cc_builder.rs#L379-L397) does not override CFLAGS when using the cc builder. Setting `AWS_LC_SYS_CFLAGS=$(CFLAGS) -O0` may turn off optimization for all modules, which is not what we want. Let's just go ahead using the CMake builder.
